DATA:
  IMG_W: 512
  IMG_H: 256
  VAL_BATCH_SIZE: 16
MODEL:
  TYPE: swin
  NAME: stocks-semihard
  DROP_PATH_RATE: 0.2
  FEATURE_SIZE: 2048
  SWIN:
    IN_CHANS: 3
    EMBED_DIM: 128
    DEPTHS: [2,2]
    NUM_HEADS: [16,32]
    WINDOW_SIZE: 16
    PATCH_SIZE: 4
    PATCH_H: 4
    PATCH_W: 8
    AVG_POOL: False
SAVE_FREQ: 10
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.0e-6
  CLIP_GRAD: 0.0
  TRIPLET_SELECTION: semi_hard
  TRIPLET_ENABLE: True
  PBOUNDS: [20,20,40,40,80,80,100,100,100]
  NBOUNDS: [6000,5000,4000,3200,2700,2250,1800,1600,1400]
  SWITCH: [0,10,15,20,25,30,35,40,45]
  LOAD_MAT: False
  MARGIN: 0.10
  CUDA: "cuda:1"
  TRIPLET_WEIGHT: 1.0
AMP_OPT_LEVEL: "O0"
